---
title: "Untitled"
author: "112024507 黃承平"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### true: heredity + analysis: heredity

```{r}
library(matlib)
set.seed(1009)
n <- 1000
m1 <- 2
m2 <- 1
sigma <- 0.5

design <- design_ShiTang2
beta_place <- matrix(0, n, m1)
true_identify <- numeric(n)
names(true_identify) <- c('1', '2', '3')

combination_ME <- combn(16, m1)

start_time <- Sys.time()
for (i in 1:n) {
  # generate y
  beta <- numeric(ncol(design))
  place <- sample(16, m1)
  FI_place <- sample(1:choose(m1, 2), m2)
  beta[place] <- rbinom(m1, 1, 0.5)*2-1
  y <- design %*% beta + rnorm(nrow(design), 0, sigma)
  columns_true <- design[, place]
  for  (j in FI_place){
    y <- y + 0.5*sample(c(-1, 1), 1)*design[, combn(place, 2)[1, j]]*design[, combn(place, 2)[2, j]]
    columns_true <- cbind(columns_true, design[, combn(place, 2)[1, j]]*design[, combn(place, 2)[2, j]])
  }
  # Use BIC to select factors
  BIC_list <- numeric(choose(16, m1))
  BIC_list2 <- numeric(choose(choose(m1, 2), m2))
  
  for (j in 1:choose(16, m1)){
    X <- design[, combination_ME[, j]]
    tryCatch({
      SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X %*% Ginv(t(X) %*% X) %*% (t(X) %*% y)))^2)
    })
    # SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    BIC_list[j] <- n*log(SSres/n) + m1*log(n)
  }
  X_temp <- design[, combination_ME[, which.min(BIC_list)]]
  # y1 <- y - X_temp %*% solve(t(X_temp) %*% X_temp, t(X_temp) %*% y)
  
  combination_2fi <- combn(combination_ME[, which.min(BIC_list)], 2)
  for (k in 1:choose(ncol(combination_2fi), m2)){
    for (l in 1:m2){
      chosen_2fi <- combn(ncol(combination_2fi), m2)[l, k]
      X_temp1 <- cbind(X_temp, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
    }
    tryCatch({
      SSres <- sum((y-(X_temp1 %*% solve(t(X_temp1) %*% X_temp1, t(X_temp1) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X_temp1 %*% Ginv(t(X_temp1) %*% X_temp1) %*% (t(X_temp1) %*% y)))^2)
    })
    # SSres <- sum((y1-(X %*% solve(t(X) %*% X, t(X) %*% y1)))^2)
    BIC_list2[k] <- n*log(SSres/n) + m1*log(n)
  }
  
  columns_pred <- design[, combination_ME[, which.min(BIC_list)]]
  kstar <- which.min(BIC_list2)
  for (cols in 1:m2) {
    chosen_2fi <- combn(ncol(combination_2fi), m2)[cols, kstar]
    columns_pred <- cbind(columns_pred, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
  }
  
  for (p in 1:ncol(columns_pred)){
      column_pred <- columns_pred[, p]
      if(any(apply(columns_true, 2, function(x) sum(x * column_pred)==length(x)))) {
        true_identify[i] <- true_identify[i] + 1
      }
  }
  
}

end_time <- Sys.time()
print(end_time - start_time)
table(true_identify)
mean(true_identify)
```

### true: !heredity + analysis: !heredity

```{r}
set.seed(1009)
n <- 1000
m1 <- 3
m2 <- 1
sigma <- 0.5

design <- design_ShiTang2
beta_place <- matrix(0, n, m1)
true_identify <- numeric(n)
ties <- numeric(n)
names(true_identify) <- c('1', '2', '3')

combination_ME <- combn(16, m1)

start_time <- Sys.time()
for (i in 1:n) {
  # generate y
  beta <- numeric(ncol(design))
  place <- sample(16, m1)
  FI_place <- sample(1:choose(16, 2), m2)
  beta[place] <- rbinom(m1, 1, 0.5)*2-1
  y <- design %*% beta + rnorm(nrow(design), 0, sigma)
  columns_true <- design[, place]
  for  (j in FI_place){
    y <- y + 0.5*sample(c(-1, 1), 1)*design[, combn(1:16, 2)[1, j]]*design[, combn(1:16, 2)[2, j]]
    columns_true <- cbind(columns_true, design[, combn(1:16, 2)[1, j]]*design[, combn(1:16, 2)[2, j]])
  }
  # Use BIC to select factors
  BIC_list <- numeric(choose(16, m1))
  BIC_list2 <- numeric(choose(choose(16, 2), m2))
  
  for (j in 1:choose(16, m1)){
    X <- design[, combination_ME[, j]]
    tryCatch({
      SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X %*% Ginv(t(X) %*% X) %*% (t(X) %*% y)))^2)
    })
    # SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    BIC_list[j] <- n*log(SSres/n) + m1*log(n)
  }
  X_temp <- design[, combination_ME[, which.min(BIC_list)]]
  
  # y1 <- y - X_temp %*% solve(t(X_temp) %*% X_temp, t(X_temp) %*% y)
  
  combination_2fi <- combn(1:16, 2)
  list_2fi <- combn(ncol(combination_2fi), m2)
  

  for (k in 1:choose(ncol(combination_2fi), m2)){
    for (l in 1:m2){
      chosen_2fi <- list_2fi[l, k]
      X_temp1 <- cbind(X_temp, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
    }
    tryCatch({
      SSres <- sum((y-(X_temp1 %*% solve(t(X_temp1) %*% X_temp1, t(X_temp1) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X_temp1 %*% Ginv(t(X_temp1) %*% X_temp1) %*% (t(X_temp1) %*% y)))^2)
      ginv_count <- ginv_count + 1
    })
    # SSres <- sum((y1-(X %*% solve(t(X) %*% X, t(X) %*% y1)))^2)
    BIC_list2[k] <- n*log(SSres/n) + m1*log(n)
  }

  
  columns_pred <- design[, combination_ME[, which.min(BIC_list)]]
  kstar <- which.min(BIC_list2)
  
  for (cols in 1:m2) {
    chosen_2fi <- combn(ncol(combination_2fi), m2)[cols, kstar]
    columns_pred1 <- cbind(columns_pred, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
  }
  
  for (p in 1:ncol(columns_pred1)){
      column_pred <- columns_pred1[, p]
      if(any(apply(columns_true, 2, function(x) sum(x * column_pred)==length(x)))) {
        true_identify[i] <- true_identify[i] + 1
      }
  }
  
  
  if (i %% 100 == 0) {
    print(i)
  }
  
}
end_time <- Sys.time()
print(end_time - start_time)
table(true_identify)
mean(true_identify)
```



### true: heredity + analysis: !heredity

```{r}
set.seed(1009)
n <- 1000
m1 <- 3
m2 <- 1
sigma <- 0.5

design <- design_ShiTang2
beta_place <- matrix(0, n, m1)
true_identify <- numeric(n)
names(true_identify) <- c('1', '2', '3')

combination_ME <- combn(16, m1)

start_time <- Sys.time()
for (i in 1:n) {
  # generate y
  beta <- numeric(ncol(design))
  place <- sample(16, m1)
  FI_place <- sample(1:choose(m1, 2), m2)
  beta[place] <- rbinom(m1, 1, 0.5)*2-1
  y <- design %*% beta + rnorm(nrow(design), 0, sigma)
  columns_true <- design[, place]
  for  (j in FI_place){
    y <- y + 0.5*sample(c(-1, 1), 1)*design[, combn(place, 2)[1, j]]*design[, combn(place, 2)[2, j]]
    columns_true <- cbind(columns_true, design[, combn(place, 2)[1, j]]*design[, combn(place, 2)[2, j]])
  }
  # Use BIC to select factors
  BIC_list <- numeric(choose(16, m1))
  BIC_list2 <- numeric(choose(choose(16, 2), m2))
  
  for (j in 1:choose(16, m1)){
    X <- design[, combination_ME[, j]]
    tryCatch({
      SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X %*% Ginv(t(X) %*% X) %*% (t(X) %*% y)))^2)
    })
    # SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    BIC_list[j] <- n*log(SSres/n) + m1*log(n)
  }
  X_temp <- design[, combination_ME[, which.min(BIC_list)]]
  # y1 <- y - X_temp %*% solve(t(X_temp) %*% X_temp, t(X_temp) %*% y)
  
  combination_2fi <- combn(1:16, 2)
  list_2fi <- combn(ncol(combination_2fi), m2)
  

  for (k in 1:choose(ncol(combination_2fi), m2)){
    for (l in 1:m2){
      chosen_2fi <- list_2fi[l, k]
      X_temp1 <- cbind(X_temp, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
    }
    tryCatch({
      SSres <- sum((y-(X_temp1 %*% solve(t(X_temp1) %*% X_temp1, t(X_temp1) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X_temp1 %*% Ginv(t(X_temp1) %*% X_temp1) %*% (t(X_temp1) %*% y)))^2)
      ginv_count <- ginv_count + 1
    })
    # SSres <- sum((y1-(X %*% solve(t(X) %*% X, t(X) %*% y1)))^2)
    BIC_list2[k] <- n*log(SSres/n) + m1*log(n)
  }

  
  columns_pred <- design[, combination_ME[, which.min(BIC_list)]]
  kstar <- which.min(BIC_list2)
  for (cols in 1:m2) {
    chosen_2fi <- combn(ncol(combination_2fi), m2)[cols, kstar]
    columns_pred <- cbind(columns_pred, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
  }
  
  for (p in 1:ncol(columns_pred)){
      column_pred <- columns_pred[, p]
      if(any(apply(columns_true, 2, function(x) sum(x * column_pred)==length(x)))) {
        true_identify[i] <- true_identify[i] + 1
      }
  }
  if (i %% 100 == 0) {
    print(i)
  }
  
}
end_time <- Sys.time()
print(end_time - start_time)
table(true_identify)
mean(true_identify)
```

### true: !heredity + analysis: heredity

```{r}
set.seed(1009)
n <- 1000
m1 <- 3
m2 <- 2
sigma <- 0.5

design <- design_ShiTang2
beta_place <- matrix(0, n, m1)
true_identify <- numeric(n)
names(true_identify) <- c('1', '2', '3')

combination_ME <- combn(16, m1)

start_time <- Sys.time()
for (i in 1:n) {
  # generate y
  beta <- numeric(ncol(design))
  place <- sample(16, m1)
  FI_place <- sample(1:choose(16, 2), m2)
  beta[place] <- rbinom(m1, 1, 0.5)*2-1
  y <- design %*% beta + rnorm(nrow(design), 0, sigma)
  columns_true <- design[, place]
  for  (j in FI_place){
    y <- y + 0.5*sample(c(-1, 1), 1)*design[, combn(1:16, 2)[1, j]]*design[, combn(1:16, 2)[2, j]]
    columns_true <- cbind(columns_true, design[, combn(1:16, 2)[1, j]]*design[, combn(1:16, 2)[2, j]])
  }
  # Use BIC to select factors
  BIC_list <- numeric(choose(16, m1))
  BIC_list2 <- numeric(choose(choose(m1, 2), m2))
  
  for (j in 1:choose(16, m1)){
    X <- design[, combination_ME[, j]]
    tryCatch({
      SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X %*% Ginv(t(X) %*% X) %*% (t(X) %*% y)))^2)
    })
    # SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
    BIC_list[j] <- n*log(SSres/n) + m1*log(n)
  }
  X_temp <- design[, combination_ME[, which.min(BIC_list)]]
  # y1 <- y - X_temp %*% solve(t(X_temp) %*% X_temp, t(X_temp) %*% y)
  
  combination_2fi <- combn(combination_ME[, which.min(BIC_list)], 2)
  for (k in 1:choose(ncol(combination_2fi), m2)){
    for (l in 1:m2){
      chosen_2fi <- combn(ncol(combination_2fi), m2)[l, k]
      X_temp1 <- cbind(X_temp, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
    }
    tryCatch({
      SSres <- sum((y-(X_temp1 %*% solve(t(X_temp1) %*% X_temp1, t(X_temp1) %*% y)))^2)
    }, error = function(e) {
      SSres <- sum((y-(X_temp1 %*% Ginv(t(X_temp1) %*% X_temp1) %*% (t(X_temp1) %*% y)))^2)
    })
    # SSres <- sum((y1-(X %*% solve(t(X) %*% X, t(X) %*% y1)))^2)
    BIC_list2[k] <- n*log(SSres/n) + m1*log(n)
  }
  
  columns_pred <- design[, combination_ME[, which.min(BIC_list)]]
  kstar <- which.min(BIC_list2)
  for (cols in 1:m2) {
    chosen_2fi <- combn(ncol(combination_2fi), m2)[cols, kstar]
    columns_pred <- cbind(columns_pred, 
                      design[, combination_2fi[1, chosen_2fi]]*
                        design[, combination_2fi[2, chosen_2fi]])
  }
  
  for (p in 1:ncol(columns_pred)){
      column_pred <- columns_pred[, p]
      if(any(apply(columns_true, 2, function(x) sum(x * column_pred)==length(x)))) {
        true_identify[i] <- true_identify[i] + 1
      }
  }
  
}

end_time <- Sys.time()
print(end_time - start_time)
table(true_identify)
mean(true_identify)
```


```{r}
set.seed(1009)
n <- 1000
m1 <- 2
m2 <- 1
sigma <- 0.1

design <- design_ShiTang
true_identify <- 0
rank_list <- numeric(n)

start_time <- Sys.time()
for (i in 1:n) {
  
  # generate y
  beta <- numeric(ncol(design))
  place <- sample(16, m1)
  FI_place <- sample(1:choose(m1, 2), m2)
  beta[place] <- rbinom(m1, 1, 0.5)*2-1
  y <- design %*% beta + rnorm(nrow(design), 0, sigma)
  columns_true <- design[, place]
  for  (j in FI_place){
    y <- y + 0.5*sample(c(-1, 1), 1)*design[, combn(place, 2)[1, j]]*design[, combn(place, 2)[2, j]]
  }
  
  # Use BIC to select factors
  n_candidte <- 0
  for (m in 1:(m1+m2)){
    n_candidte <- n_candidte + choose(16, m)
  }
  BIC_list <- numeric(n_candidte)
  
  count <- 1
  lowest_BIC <- Inf
  for (m in 1:(m1+m2)){
    combination <- combn(16, m)
    for (k in 1:choose(16, m)){
      d <- design[, combination[, k]]
      X <- cbind(1, d)
      tryCatch({
        SSres <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
      }, error = function(e) {
        SSres <- sum((y-(X %*% Ginv(t(X) %*% X) %*% (t(X) %*% y)))^2)
      })
      BIC_value <- nrow(design)*log(SSres/nrow(design)) + (m+1)*log(nrow(design))
      BIC_list[count] <- BIC_value
      count <- count + 1
      if (BIC_value < lowest_BIC) {
        lowest_BIC <- BIC_value
        columns_pred <- d
      }
      
    }
  }
  X <- cbind(1, columns_true)
  SSres_true <- sum((y-(X %*% solve(t(X) %*% X, t(X) %*% y)))^2)
  BIC_true <- nrow(design)*log(SSres_true/nrow(design)) + (m1+1)*log(nrow(design))
  rank_list[i] <- which(abs(sort(BIC_list) - BIC_true) < 1e-10)
  
  # If all main effect is correct, then add 1 to true_identify
  right <- 0
  for (k in 1:ncol(columns_true)){
    column_true <- columns_true[, k]
    if (any(apply(columns_pred, 2, function(x) sum(x * column_true)==length(x)))) {
      right <- right + 1
    }
  }
  if (right == m1) {
    true_identify <- true_identify + 1
  }
  
  
  if (i %% 100 == 0) {
    print(i)
  }
  
}
end_time <- Sys.time()
print(end_time - start_time)
print(true_identify)
```

